### ISSUE TITLE
LLSE中的pl.setTitle设置玩家显示标题有问题

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#1205]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2019

### LiteLoader 版本

2.12.3

### BDS 版本

1.19.73

### 发生了什么?

LLSE中的pl.setTitle(content[,type[,fadeInTime,stayTime,fadeOutTime]])设置玩家显示标题
中的staytime停留时间设置后无效，依然是默认的70tick，本来希望不适用runcmd的，现在只能又使用runcmd来实现了，希望尽快修复（淡入和淡出暂时没试过，应该没什么问题吧）

**Comment by yufengya0420** [comment]
刚刚在单人游戏内使用纯原版指令测试了一下，经测试单人模式下指令依然无效，疑似是游戏本身的问题，而不是加载器的问题，离大谱了：
/title @p title 主标题
/title @p subtitle 副标题
/title @p times 20 300 10
中间的停留时间默认是70tick，在改成300后停留时间依然是70tick，不知道为什么

**Comment by yufengya0420** [comment]
现在的问题就是无论使用加载器还是控制台还是游戏内指令都无法实现/title @p times所应该实现的效果，很烦

**Comment by ShrBox** [comment]
e.g.
```js
player.setTitle("YJSP", 5, 114, 114514, 514)
player.setTitle("YJSP", 2)
```
