### ISSUE TITLE
pl.gameMode玩家的游戏模式（0 - 3）LL文档有误？

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#1216]
### 您的建议是否与现存的某个问题相关?请描述问题?

基岩版中只有0生存，1创造，2冒险，好像没有3吧，观察者也必须是输入英文的全称才可以：/gamemode spectator

**Comment by StarsDream00** [comment]
建议转移至https://github.com/LiteLDev/Documentation

**Comment by yufengya0420** [comment]
> 建议转移至 https://github.com/LiteLDev/Documentation

我就是在这里看的呀，玩家对象里面的

**Comment by WangYneos** [comment]
观察者为6，issue将被transfer到正确的仓库
