### ISSUE TITLE
AddonHelper错误

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#1219]
### 异常模块

AddonsHelper

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.12.4

### BDS 版本

1.19.73

### 发生了什么?

给服务器存档加上了几个材质，然后开服控制台显示报错：
21:28:43 ERROR [AddonHelper] Uncaught C++ Exception Detected!
21:28:43 ERROR [AddonHelper] In parseAddonFromPath ./worlds/Bedrock level/resource_packs\BetterSnow
21:28:43 ERROR [AddonHelper] Error: Code[-1] [json.exception.type_error.302] type must be string, but is null
21:28:43 ERROR [AddonHelper] Uncaught C++ Exception Detected!
21:28:43 ERROR [AddonHelper] In parseAddonFromPath ./worlds/Bedrock level/resource_packs\ButterflyD
21:28:43 ERROR [AddonHelper] Error: Code[-1] [json.exception.type_error.302] type must be string, but is null
21:28:43 ERROR [AddonHelper] Uncaught C++ Exception Detected!
21:28:43 ERROR [AddonHelper] In parseAddonFromPath ./worlds/Bedrock level/resource_packs\KungFuPand
21:28:43 ERROR [AddonHelper] Error: Code[-1] [json.exception.type_error.302] type must be string, but is null

但是报错好像并没有影响什么，游戏内正常，材质也显示正常

**Comment by quizhizhe** [comment]
错误提示应该是有个变量啥的需要字符串，但获取到的是空的，也许需要检查下材质包文件

**Comment by ShrBox** [comment]
资源包开发者没有正确填写`manifest.json`
