### ISSUE TITLE
Error ResourcepackEncrypt ??

### ISSUE THREAD

**Issue by wcdfilll** [LiteLDev/LiteLoaderBDS#1292]
### Exceptions module

Core

### Operating System

Windows 10

### LiteLoader version

2.13.1

### BDS version

1.19.81

### What happened?

下面是译文:

我在资源包加密方面遇到一点小问题。我有下面的截图,作者能检查一下我是否做对了吗?我这样做后,我的玩家仍然可以泄露那个资源包
![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/53313122/1052b8e4-33a5-432c-99c7-1c6fb1d8ea26)

### Steps to reproduce?

None

### Relevant log output

```raw
None
```

### Plugin list

```raw
我觉得没有必要提供那个
```

**Comment by ShrBox** [comment]
资源包加密可以很容易解密，因为服务端需要把必要发送给客户端解密，客户端解密后你的资源包就是未加密的
资源包加密只能提高资源包被盗用的门槛，并不能防止资源包被解密
