### ISSUE TITLE
破坏事件bug：玩家站到别人领地外面挖床能一直掉

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#1303]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

release2.14.0 

### BDS 版本

1.20.0

### 发生了什么?

iland插件-破坏事件：
站到别人领地外面挖床能一直掉
iland作者说应该是LL的问题
以下是视频文件：
[2023-06-21 10-18-53.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11811947/2023-06-21.10-18-53.zip)

### 复现此问题的步骤

1.安装BDS和LL
2.安装iland插件
3.站到别人领地外面挖床

### 有关的日志/输出

```raw
结果就是可以一直刷床的掉落物
```

**Comment by StarsDream00** [comment]
fd2373f
