### ISSUE TITLE
破坏事件bug：玩家破坏陶罐可以一直刷-iland

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#1306]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.14.1

### BDS 版本

1.20.0.1

### 发生了什么?

![V(`0JHT79Y1~W`O)(1`QD77](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/62beeb37-223c-4555-93e2-8091ee77e677)

> 
[视频.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11819655/default.zip)

**Comment by ShrBox** [comment]
#1303
