### ISSUE TITLE
LLSE：getCurrentExperience获取经验等级不准确

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#1312]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.14.1

### BDS 版本

1.20.0

### 发生了什么?

![%NVK72AUNQ{ 6L5O~LSCA0U](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/6e4fee8f-df7b-4ebe-80db-8dc2d370cf3b)

### 复现此问题的步骤

1.创建test.js文件，写入一下代码：
const xpcmd = mc.newCommand("showxp", "展示自己的经验等级", PermType.Any);
	xpcmd.overload([]);
	xpcmd.setCallback((_cmd, ori, _out, _res) => {
		if (ori.player) {
			mc.broadcast(`§b[玩家] §e${ori.player.realName} §b展示了Ta的§a[经验等级]§r -> §a${ori.player.getCurrentExperience()} 级(${ori.player.getTotalExperience()})`)
		}
	});
	xpcmd.setup();
2.进入游戏输入/showxp指令，自己明明是118级却显示289级

**Comment by yufengya0420** [comment]
![$8QGUPZKW X`ZH2W2 I7T58](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/c88ee9e3-dabc-417c-99f5-13c8973acb66)

**Comment by yufengya0420** [comment]
另外，getTotalExperience获取的数值我没测，估计也不准确

**Comment by StarsDream00** [comment]
experience是经验值，level才是经验

**Comment by StarsDream00** [comment]
need close as not planned

**Comment by StarsDream00** [comment]
以及发代码请用markdown
