### ISSUE TITLE
mc.getTime(2) 获取的游戏内已流逝的天数好像不准确

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#1323]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.14.1

### BDS 版本

1.20.1

### 发生了什么?

![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/fafccc39-ebbc-4565-b830-f1f2cd1c0aa5)
![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/443f82f0-ffda-47c8-b2db-d9be51458866)
获取的游戏内已流逝的天数好像不准确，我服务器都开了一个多月了，还是十几天

**Comment by yufengya0420** [comment]
> 此LLSE API调用的是BDS内置的函数，数据来源于BDS，所以不是我们的问题，建议提交到bugs.mojang.com

会不会和玩家睡觉百分比有关系，我那个插件的原理是直接控制台执行指令修改时间，这样的话是不是就改成了当天的日出时间，所以实际上并没有跳过黑夜，所以导致了并没有计算天数？

**Comment by RimuruChan** [comment]
@yufengya0420 。。大概率是
