### ISSUE TITLE
请尽快更新（ 或许是我没发现？）

### ISSUE THREAD

**Issue by crowdedplus** [LiteLDev/LiteLoaderBDS#1350]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 10

### LiteLoader 版本

2.15.0

### BDS 版本

1.20.30.02

### 发生了什么?

无法将服务器从1.20.15升级到1.20.30，没有对应的liteloader。

**Comment by Hosiyume** [comment]
spam

**Comment by crowdedplus** [comment]
emmm所以更新了还是没更新呢，你这么说我也不能理解
