### ISSUE TITLE
bedrock_server.exe inconvenience

### ISSUE THREAD

**Issue by wcdfilll** [LiteLDev/LiteLoaderBDS#145]
After LL 2.0 was released, I found the disadvantage of having to update LL is that when running SymDB2.exe, it deletes the bedrock_server.exe file and replaces it with bedrock_server_mod.exe. This is detrimental every time I update the LL, when I update the LL to a new version, I have to find the bedrock_server.exe file to run the SymDB2 file again for the latest updated LL version. I don't know if it's the "Trust Windows app" issue?

**Comment by dreamguxiang** [comment]
You only need to rerun SymDB2 when you update the BDS version

**Comment by dreamguxiang** [comment]
.\symdb2 -h 可以看到他的用法

**Comment by WangYneos** [comment]
@wcdfilll well you will need to rerun SymDB2.exe after BDS update. BTW  add -keepOri param will tell SymDB2 not to delete the original one

**Comment by wcdfilll** [comment]
I don't update often, because the LL platform is based on the official version of minecraft, so I take advantage of it by copying out many worlds to each server and splitting it up to make it easier to manage each world instead of having to have many worlds in one. file server. Because of having to disassemble the plugin again and again if I don't do it the above way, I choose that each file server has its own world and its own settings.
