### ISSUE TITLE
使用jsr强开官方jse报错

### ISSUE THREAD

**Issue by dzx-dzx** [LiteLDev/LiteLoaderBDS#15]
![image](https://user-images.githubusercontent.com/31068367/112183694-75a98300-8c39-11eb-89b0-4c751acfe4d2.png)

![image](https://user-images.githubusercontent.com/31068367/112177431-de8dfc80-8c33-11eb-98f1-f7f83ff6acd7.png)
平台是ll+csr+jsr。

**Comment by ShrBox** [comment]
尝试将`C:\Windows\System32\Chakra.dll`放入`plugins\lib\`

**Comment by dzx-dzx** [comment]
> 
> 
> 尝试将`C:\Windows\System32\Chakra.dll`放入`plugins\lib\`

呃……`lib`不是自动创建的文件夹，我需要更新吗？

**Comment by ShrBox** [comment]
> > 尝试将`C:\Windows\System32\Chakra.dll`放入`plugins\lib\`
> 
> 呃……`lib`不是自动创建的文件夹，我需要更新吗？

不会自动创建

**Comment by dzx-dzx** [comment]
恐怕依然崩溃。

**Comment by ShrBox** [comment]
这里给出另一种办法，用其它非劫持Chakra库的加载器（如[NanoLauncher](https://www.minebbs.com/resources/nanolauncher-win-bds.866/)）来加载LiteLoader，但会导致依赖修改后的Chakra的插件无法加载
