### ISSUE TITLE
管好你自己

### ISSUE THREAD

**Issue by xlandc812** [LiteLDev/LiteLoaderBDS#181]
管好你自己应该做的，不该做的不要做。
幸运列表：
177-----635
133-----249
150-----105
139-----606
188-----952
保护个人隐去5位

**Comment by xlandc812** [comment]
@yqs112358 @RimuruChan @Redbeanw44602 @xiaoqch @Jasonzyt @ShrBox @dreamguxiang

**Comment by yqs112358** [comment]
乐，除了匿名邮件您还会干啥




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月26日(星期三) 中午12:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LiteLDev/LiteLoaderBDS] 管好你自己 (Issue #181)





 
@yqs112358 @RimuruChan @Redbeanw44602 @xiaoqch @Jasonzyt @ShrBox @dreamguxiang

**Comment by xlandc812** [comment]
> 乐，除了匿名邮件您还会干啥
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年1月26日(星期三) 中午12:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [LiteLDev/LiteLoaderBDS] 管好你自己 (Issue #181) @yqs112358 @RimuruChan @Redbeanw44602 @xiaoqch @Jasonzyt @ShrBox @dreamguxiang — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

硬汉，可以继续
