### ISSUE TITLE
It's not work on 1.18.11.01

### ISSUE THREAD

**Issue by chimon89** [LiteLDev/LiteLoaderBDS#194]
Logs:

`
[Crashed!]
-- Unhandled Exception in -> 
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Event::OutputEventError at 0x7FF93690CA00  [LiteLoader.dll]
-- At File  : Line -1643947488 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function DedicatedServer::start at 0x7FF7806A82B0  [bedrock_server_mod.exe]
-- At File  : Line -1643947488 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function main at 0x7FF7806D2300  [bedrock_server_mod.exe]
-- At File  : Line -1643947488 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function __scrt_common_main_seh at 0x7FF781B22174  [bedrock_server_mod.exe]
-- At File  : Line -1643947488 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BaseThreadInitThunk at 0x7FF99FCA54D0  [KERNEL32.DLL]
-- At File  : Line -1643947488 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function RtlUserThreadStart at 0x7FF9A0984830  [ntdll.dll]
-- At File  : Line -1643947488 
[TrackBack] Function ???????? at 0x????????
`

**Comment by littlegao233** [comment]
haven't supported it yet.
LiteLoaderTeam currently working on the beta branch and soon will support 1.18.11.

**Comment by chimon89** [comment]
work well by actions, thx.
