### ISSUE TITLE
表单滑块失效

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#206]
**Describe the bug**

自定义表单构建器部分（.addStepSlider）default : Integer
（可选参数）步进滑块默认初始选项。序号从 0 开始编号
默认为 0，即滑块位于滑块行的开头，无论选择哪一个选项，最后给玩家发送表单的结果都是第一个选项（即默认为0的第一个选项）

此bug常见于所有发送自定义表单的插件中的（向表单内增加一行步进滑块）

**Comment by Jasonzyt** [comment]
LLSE？

**Comment by yufengya0420** [comment]
> LLSE？

对的，原LXL插件的表单出现了以上的问题

**Comment by yqs112358** [comment]
已修复，请等待今晚LL更新
