### ISSUE TITLE
Errors while compiling the source code. Help me please!

### ISSUE THREAD

**Issue by krusalovorg** [LiteLDev/LiteLoaderBDS#22]
![image](https://user-images.githubusercontent.com/70585437/115119591-40831d00-9fba-11eb-90f8-c82e355e1cb8.png)
Errors while compiling the source code. Help me please! I use Visual Studio

**Comment by ShrBox** [comment]
![image](https://user-images.githubusercontent.com/53301243/115131470-f71ee600-a02a-11eb-9e38-7eb142acbe5f.png)

**Comment by krusalovorg** [comment]
Thanks! It is work!
