### ISSUE TITLE
Name Switching list problem

### ISSUE THREAD

**Issue by jesdicaDomo** [LiteLDev/LiteLoaderBDS#225]
![image](https://user-images.githubusercontent.com/12781303/153713142-3956c1fc-f5b9-4b00-a6b9-6bc25e9f7c19.png)

I'm having an issue where the toggle list doesn't match the selected value. in the preview It will always run the first list.

 - OS: [e.g. Windows Server 2019]
 - LiteLoader Version [e.g. 2.1.0]

**Comment by dreamguxiang** [comment]
#209

**Comment by dreamguxiang** [comment]
Fixed 6b3aaabd12143782cb383dd1fc81ef046c2bd1c6 ,Waiting for the new version
