### ISSUE TITLE
LL插件问题反馈

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#234]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version 版本

LiteLoader-2.1.1

### BDS version  BDS版本

1.18.11

### What happened? Please describe your problem. 发生了什么?请描述你的问题

使用LL插件OutputFilter.dll的屏蔽词插件情况下，在配置文件为包括：banlist.txt（Running AutoCompaction），控制台依然会输出Running AutoCompaction...
以上情况经过测试，在配置完全一模一样的两个vps上，第一个vps运作正常，第二个vps并不能有效屏蔽此输出，不知道什么原因

### Steps to reproduce? 复现此问题的步骤

1.装LL2.1.1
2. 装屏蔽词插件
3. 开服
4. 等待控制台输出

**Comment by yufengya0420** [comment]
![压缩](https://user-images.githubusercontent.com/99462074/153739379-61b4f7ff-c81a-410a-8586-339db66c09f8.png)

**Comment by yufengya0420** [comment]
所有vps都不能屏蔽，真坏了

**Comment by ShrBox** [comment]
插件问题建议反馈给开发者，而不是在LL的Issue里反馈
