### ISSUE TITLE
更新LL2.1.2后控制台报错刷屏

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#251]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version 版本

LiteLoader-2.1.2

### BDS version  BDS版本

1.18.11

### What happened? Please describe your problem. 发生了什么?请描述你的问题

![image](https://user-images.githubusercontent.com/99462074/153908744-7e698e07-3422-468d-8b30-871e4d657264.png)
更新LL2.1.2后开服控制台频繁刷屏

### Steps to reproduce? 复现此问题的步骤

1. 更新2.1.2
2. 开服
3....

**Comment by pa733** [comment]
麻烦提供一下插件截图

**Comment by yufengya0420** [comment]
![EXFIYGJ (YEU_50% MF5D0R](https://user-images.githubusercontent.com/99462074/153910954-cf4efa21-a849-4a6c-be48-3916f84d6b2c.png)

**Comment by yufengya0420** [comment]
![DVKYRVVSR`VH X`)3)7V 0I](https://user-images.githubusercontent.com/99462074/153997183-bbc489f5-638f-4f27-9792-4e3a9f928c90.png)

**Comment by dreamguxiang** [comment]
可以把plugins打包发一下吗

**Comment by yufengya0420** [comment]
可以稍等

**Comment by yufengya0420** [comment]
https://wwp.lanzouq.com/iX6ex003shrg

**Comment by yqs112358** [comment]
你是不是有插件会自己热卸载热加载

**Comment by yufengya0420** [comment]
有个tmet的自动更新一分钟获取一次联网不知道是不是这个

**Comment by yqs112358** [comment]
很有可能

**Comment by yufengya0420** [comment]
tmet是js，报错是有时候是script-engine-js，有时候是script-engine-lua，lua只有一个iland，不确定是哪个插件造成的，也不知道是不是加载器问题

**Comment by yufengya0420** [comment]
而且这个报错是概率触发

**Comment by dreamguxiang** [comment]
测试了几次，没复现出来

**Comment by yqs112358** [comment]
有无复现办法可以提供一下？

**Comment by yqs112358** [comment]
尝试卸载lxlws插件然后观察情况

**Comment by yufengya0420** [comment]
![7BM{1FYGMDQ3O50Q1)Q)3`K](https://user-images.githubusercontent.com/99462074/154506558-56c20c6a-7c5a-4450-b6a3-bf35195f29ec.png)

**Comment by yufengya0420** [comment]
另一位服主的截图：
![3N F~YK$~Z$XE3D4(DCZ SP](https://user-images.githubusercontent.com/99462074/154506780-0dc9752e-80d8-42fb-abd5-9260f4190d54.jpg)

**Comment by yufengya0420** [comment]
自定义防爆？他的和我的插件只有这一个重复的

**Comment by yufengya0420** [comment]
我再试试不加插件运行一天试试

**Comment by yufengya0420** [comment]
基本已经锁定是插件内只要含有settimeout就会导致这个报错刷屏

**Comment by yufengya0420** [comment]
![71_COUY8PKT (APUPIVRK~S](https://user-images.githubusercontent.com/99462074/154976256-785c7642-35da-483e-8dbf-b4f1b6d56d26.png)

**Comment by yufengya0420** [comment]
可以尝试只加入一个插件：fuckitementity.js然后开服等待。。

**Comment by yqs112358** [comment]
插件能发一下吗

**Comment by yufengya0420** [comment]
[新建文件夹.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/8110078/default.zip)

**Comment by xiaoqch** [comment]
> schedule系统是整个LL通用的系统，这里的报错是套在timetask回调上的安全检测 如果有未捕获异常，必定是回调所在的插件抛出，所以问题只可能在插件发生 这里是异常处理截获异常之后的报告，如果不加处理完全可以不显示，但是后续完全可能造成bug甚至崩溃，有报错显示出来说明插件确实有问题存在

如果只是llse插件问题应该是在llse里就能捕获异常并打印llse插件信息，但是这里是ll捕获的异常然后打印的是llse的信息

**Comment by yqs112358** [comment]
> 可以尝试只加入一个插件：fuckitementity.js然后开服等待。。

已经在游戏中挂机一小时，完全无问题
不知如何复现

**Comment by yufengya0420** [comment]
有时候开服24小时才会有，一小时没有很正常，有时候开服就刷，有时候六个小时都不刷

**Comment by yufengya0420** [comment]
跟买彩票差不多，，

**Comment by WangYneos** [comment]
不稳定复现的问题暂时无法解决

**Comment by yufengya0420** [comment]
![Screenshot_20220222_202357_com microsoft rdc androidx](https://user-images.githubusercontent.com/99462074/155131788-03598119-144e-4c5f-890b-589c1f4c8f75.jpg)
反正我每次打开服务器都是这样的，，

**Comment by yqs112358** [comment]
在内测群下最新的beta测试一下，可能有所缓解

**Comment by yufengya0420** [comment]
好的

**Comment by yqs112358** [comment]
内测群最新BETA已经缓解
