### ISSUE TITLE
热重载指令概率性失效

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#293]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

LiteLoader-2.1.3

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

在控制台输入热重载指令ll reload 插件名字 或 lxl reload 插件名字 失效 并 报错
![V675A)L_D{`VRPR}IE)2RDY](https://user-images.githubusercontent.com/99462074/156480262-52faf28d-b316-48e8-89d8-a806897146a5.png)

### Steps to reproduce? 复现此问题的步骤

1.随便热重载一个插件
2.概率性热重载失败

**Comment by xiaoqch** [comment]
试试最新构建问题是否仍存在？

**Comment by xiaoqch** [comment]
此bug应该在修复动态指令（commit [56a012d](https://github.com/LiteLDev/LiteLoaderBDS/commit/56a012d90176c35995dfc71f05868c7de6482873)）时一同修复，此issue关闭，如问题仍存在，请重新打开此issue
