### ISSUE TITLE
LLSE无法重载插件

### ISSUE THREAD

**Issue by aolong1234** [LiteLDev/LiteLoaderBDS#316]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.3

### BDS version   BDS版本

1.18.12.01

### What happened? 发生了什么问题?

llse没办法重载插件了一直说失败
![634873151a62f05a](https://user-images.githubusercontent.com/46416509/159616948-6ad05664-0596-48be-92b6-7d8b4e3a8251.jpg)

### Relevant log output 有关的日志/输出

```shell
fail to reload plugin
```

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/159617601-c5dd24a4-e66e-4014-b207-284f42a34180.png)

**Comment by dreamguxiang** [comment]
ll list看一下
