### ISSUE TITLE
/tpr

### ISSUE THREAD

**Issue by DShuGui** [LiteLDev/LiteLoaderBDS#32]
try
/tpr

**Comment by Sysca11** [comment]
如果你是中国人，希望你能用现代汉语完整表达你的意思。
If not,plz provide more detailed information(etc. server console log).
"try /tpr"两行字没有任何实际信息量，如果你认为你的服务器的/tpr行为不符合预期，且希望社区帮你测试，请给出你服务器的ip端口。
