### ISSUE TITLE
Add 'anti-nuke' feature

### ISSUE THREAD

**Issue by wcdfilll** [LiteLDev/LiteLoaderBDS#376]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

i am facing a problem, i am using a plugin with certain block breaker that will get currency, it is an LLSE plugin. The problem here is that when I turn on the server-authoritative-block-breaking=true function, I get an error, just the player who touches the block without destroying it can get the money. I don't have a solution for this, so I want to add antinuke function in LLanticheat. Thanks for read.

**Comment by dreamguxiang** [comment]
fixed 7e18c0f1d8581633149d3ff5c590180f571ac87d
