### ISSUE TITLE
( LiteLoaderBDS 2.2.0 ) Bug BlackScreen & Server Cached Console Hang

### ISSUE THREAD

**Issue by LemonCraft-11** [LiteLDev/LiteLoaderBDS#378]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.2.0

### BDS version   BDS版本

1.18.30.04

### What happened? 发生了什么问题?

Some players have a black screen & Console suddenly stops working. without cause and not showing log or dump

### Steps to reproduce? 复现此问题的步骤

1.Install LiteLoaderBDS in 3 devices
2.All Console Hangs, but the occurrence time is different.

### Plugin list 插件列表

![image](https://user-images.githubusercontent.com/74866868/165096907-c99c904b-672e-4b0a-9cdf-07bc8a5daa5b.png)
![image](https://user-images.githubusercontent.com/74866868/165096971-1061ed44-f434-48df-b99e-bc1d6dfb53d8.png)

**Comment by jesdicaDomo** [comment]
มันน่าจะบัคจาก render dragon ที่ตัวเกมเปลี่ยนมาใช้เอนจิ้นนี้

**Comment by LemonCraft-11** [comment]
> อาจเป็นข้อผิดพลาดจาก Render Dragon ที่เกมเปลี่ยนไปใช้ engin หรืออย่างอื่น

I fixed it, it's at ResoucePack.

**Comment by StarsDream00** [comment]
need to close
