### ISSUE TITLE
onDestroyBlock监听在1.18.32版本中工作异常

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LiteLoaderBDS#397]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.2.2

### BDS version   BDS版本

1.18.32.02

### What happened? 发生了什么问题?

监听玩家破坏方块并执行其他操作，破坏一个方块会连续触发两次，不应该触发两次

### Steps to reproduce? 复现此问题的步骤

1.准备好LL2.2.2的BDS服务端1.18.32.02,
2.创建js文件
3.写入以下：
mc.listen("onDestroyBlock",() => {
    log(`test`);
})
4.扔到plugins
5.开服测试
6.随便破坏一个方块

### Relevant log output 有关的日志/输出

```shell
19:37:41 INFO [TEST] test
19:37:41 INFO [TEST] test
```

**Comment by dreamguxiang** [comment]
Fixed
