### ISSUE TITLE
服务器材质包无法加载

### ISSUE THREAD

**Issue by hanximeng** [LiteLDev/LiteLoaderBDS#40]
使用在resource_packs下添加材质包及在地图目录添加文件的方法，但是并没有反应，进服务器时也没有提醒下载资源包，用原生BDS Win版却可以。

**Comment by hanximeng** [comment]
找到原因了，材质包名称是中文导致的

**Comment by yqs112358** [comment]
以后别乱开Issue好吧
确定情况再说
