### ISSUE TITLE
It doesn't seem to work with Iland.

### ISSUE THREAD

**Issue by jesdicaDomo** [LiteLDev/LiteLoaderBDS#411]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

LiteLoader 2.2.4

### BDS version   BDS版本

1.18.31

### What happened? 发生了什么问题?

When the new version is updated It seems to be able to smash blocks in the Protect region.

**Comment by StarsDream00** [comment]
please give this feedback to iLand author first

**Comment by Jasonzyt** [comment]
https://github.com/LiteLScript-Dev/iLand-Core/issues
go there and submit an issue plz
