### ISSUE TITLE
Server Crash ( How to fix )

### ISSUE THREAD

**Issue by LemonCraft-11** [LiteLDev/LiteLoaderBDS#463]
### Exceptions module

Core

### Operating System

Windows Server 2019

### LiteLoader version

2.3.0

### BDS version

1.19.0

### What happened?

Crash and Stacktrace
Link download : https://gofile.io/d/bzBcEd

**Comment by StarsDream00** [comment]
remove BEPlaceholderAPI

**Comment by LemonCraft-11** [comment]
> ลบ BEPlaceholderAPI จากนั้นรอการอัปเดต
the problem persists
https://gofile.io/d/EGm53k

**Comment by LemonCraft-11** [comment]
> remove BEPlaceholderAPI, then wait for update

the problem persists (Download Crash )
Link : https://gofile.io/d/EGm53k

**Comment by LemonCraft-11** [comment]
Open the new issue
