### ISSUE TITLE
示例代码无法运行，能否帮帮我

### ISSUE THREAD

**Issue by XingShuyu** [LiteLDev/LiteLoaderBDS#50]
如图
![71ccd90491cca2f](https://user-images.githubusercontent.com/82715884/130338844-42aaccc3-d866-40d7-b29c-423f68c1f643.png)
我按照文档来配置，但是连示例代码都无法运行

**Comment by WangYneos** [comment]
自行检查头文件引入，请尝试编译LL范例插件[LiteLoaderPlugins](https://github.com/LiteLDev/LiteLoaderPlugins),如果仍无法通过编译，请前往telegram/qq联系
