### ISSUE TITLE
两个服务端不能都打开，一个已打开在运行，再打开另外一个会崩溃

### ISSUE THREAD

**Issue by leoweyr** [LiteLDev/LiteLoaderBDS#52]
只装LiteLoader情况下，会出现两个服务端不能都打开，一个已打开在运行，再打开另外一个会崩溃，崩溃时是在另外一个服务端就要准备监听端口时崩溃的。测试时已设置端口排除端口占用的情况
以下是测试历史，最早发现问题是在LiteXLoader，后来逐一排查是LiteLoader本身出现的问题
![image](https://user-images.githubusercontent.com/58080150/131535900-cde195fc-b339-442e-ab5c-ebac67c6e9c2.png)

**Comment by ShrBox** [comment]
这是Bedrock Dedicated Server自身的问题，你可以尝试去掉目录下的Chakra.dll，问题依然会复现
