### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by jesdicaDomo** [LiteLDev/LiteLoaderBDS#531]
### Exceptions module

Core

### Operating System

Windows Server 2019

### LiteLoader version

LiteLoader 2.4.0 beta

### BDS version

1.19.10

### What happened?

StackTrace] Function ???????? at 0x7FFED6335C02  [AntiToolbox.dll]
[StackTrace] Function EndTag::set at 0x7FFED06E5D80  [LiteLoader.dll<2.4.0.2289 DEBUG>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFED06E606A  [LiteLoader.dll<2.4.0.2289 DEBUG>]
[StackTrace] Function VanillaServerNetworkHandler::handle at 0x7FF768279540  [bedrock_server_mod.exe<1.19.10.03>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF768279951  [bedrock_server_mod.exe<1.19.10.03>]
[StackTrace] Function NetworkHandler::_sortAndPacketizeEvents at 0x7FF7685B8EB0  [bedrock_server_mod.exe<1.19.10.03>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7685B9498  [bedrock_server_mod.exe<1.19.10.03>]
[StackTrace] Function <lambda_37d2627b9703ec3c85a127e9134c5ccf>::operator() at 0x7FF7685B7A40  [bedrock_server_mod.exe<1.19.10.03>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7685B7C56  [bedrock_server_mod.exe<1.19.10.03>]
[StackTrace] Function NetworkHandler::runEvents at 0x7FF7685BBEA0  [bedrock_server_mod.exe<1.19.10.03>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7685BBF01  [bedrock_server_mod.exe<1.19.10.03>]
[StackTrace] Function Minecraft::update at 0x7FF768A860F0  [bedrock_server_mod.exe<1.19.10.03>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF768A8766D  [bedrock_server_mod.exe<1.19.10.03>]
[StackTrace] Function ServerInstance::_update at 0x7FF768A9CBE0  [bedrock_server_mod.exe<1.19.10.03>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF768A9CCDD  [bedrock_server_mod.exe<1.19.10.03>]
[StackTrace] Function <lambda_a0aefe274f5913ecbd2fdf009aa305ae>::operator() at 0x7FF768A9B210  [bedrock_server_mod.exe<1.19.10.03>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF768A9B645  [bedrock_server_mod.exe<1.19.10.03>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_a0aefe274f5913ecbd2fdf009aa305ae> >,0> at 0x7FF768A985E0  [bedrock_server_mod.exe<1.19.10.03>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF768A985EE  [bedrock_server_mod.exe<1.19.10.03>]
[StackTrace] Function recalloc at 0x7FFEFFFC6AF0  [ucrtbase.dll<6.2.20348.1>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFEFFFC6B4C  [ucrtbase.dll<6.2.20348.1>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFF00994EC0  [KERNEL32.DLL<6.2.20348.740>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFF00994ED0  [KERNEL32.DLL<6.2.20348.740>]
[StackTrace] Function RtlUserThreadStart at 0x7FFF0231E370  [ntdll.dll<6.2.20348.803>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFF0231E39B  [ntdll.dll<6.2.20348.803>]

**Comment by Jasonzyt** [comment]
Have you solved it yourself?
