### ISSUE TITLE
player join crash server

### ISSUE THREAD

**Issue by HoLyMosquito487** [LiteLDev/LiteLoaderBDS#827]
### Exceptions module

PeEditor

### Operating System

Windows Server 2019

### LiteLoader version

2.7.0-beta

### BDS version

554

### What happened?

![image](https://user-images.githubusercontent.com/104082600/191905688-530c95e6-3909-4b62-b3c2-b98c6cf9456c.png)

### Plugin list

```shell
no plugins
```

**Comment by dreamguxiang** [comment]
#828

**Comment by dreamguxiang** [comment]
Fixed
