### ISSUE TITLE
player join crash

### ISSUE THREAD

**Issue by HoLyMosquito487** [LiteLDev/LiteLoaderBDS#829]
### Exceptions module

PeEditor

### Operating System

Windows Server 2019

### LiteLoader version

2.7.0-dev

### BDS version

554

### What happened?

![image](https://user-images.githubusercontent.com/104082600/191948044-86f620b6-6c91-4aed-8465-269e8a93c3c4.png)

### Plugin list

```shell
not plugins
```

**Comment by dreamguxiang** [comment]
try d785e9b60e1a466a9f3333c3a390594b5013daf7

**Comment by HoLyMosquito487** [comment]
Try fix https://github.com/LiteLDev/LiteLoaderBDS/issues/828 player 
still can't login to the server , crash

**Comment by dreamguxiang** [comment]
Try a2e8e3092b3484012b125d30f796669a8cd42917

**Comment by ShrBox** [comment]
Download corresponding pdb file and send the screenshot

**Comment by dreamguxiang** [comment]
Fixed 225dfb6e05eb97e3a945829aa4759fc8a188afe5
