### ISSUE TITLE
LLse增加setAbility

### ISSUE THREAD

**Issue by Hepaw** [LiteLDev/LiteLoaderBDS#893]
### 您的建议是否与现存的某个问题相关?请描述问题?

想使用脚本插件设置玩家的Ability

### 您认为还缺少什么?如何解决您的问题?

增加setAbility

**Comment by dreamguxiang** [comment]
pl.setAbility(AbilityIDs,value)

**Comment by dreamguxiang** [comment]
文档还未更新同步
