### ISSUE TITLE
LLSE物品对象增加it.image属性

### ISSUE THREAD

**Issue by HaiPaya** [LiteLDev/LiteLoaderBDS#902]
### 您的建议是否与现存的某个问题相关?请描述问题?

在制作商店插件时需要获取物品对应的图标

### 您认为还缺少什么?如何解决您的问题?

物品对象增加it.image属性

**Comment by quizhizhe** [comment]
图像内容不在服务器处理，比较难实现

**Comment by StarsDream00** [comment]
材质包可能会修改物品对应的图片导致原版路径与客户端路径不一致

**Comment by OEOTYAN** [comment]
可以自行通过材质包自定义保留字实现，服务端不提供材质相关功能。
