### ISSUE TITLE
LLse粒子生成器显示不全｜卡顿

### ISSUE THREAD

**Issue by HaiPaya** [LiteLDev/LiteLoaderBDS#905]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.8.1

### BDS 版本

1.19.41

### 发生了什么?

在使用粒子生成器生成立方体时有几率显示不全｜不显示
![7EAD22F9-AE08-4772-BB9A-C50DFD9294A2](https://user-images.githubusercontent.com/112671464/202893470-7df4fff9-9a60-4e8b-87a9-905fa9717b47.png)
![375D08E1-832F-4BDE-B041-654D52A2258B](https://user-images.githubusercontent.com/112671464/202893471-b40f0788-3d0d-447a-a10e-de540ceef9ef.png)
![7677B1BE-1102-42FE-81B4-B0108B978215](https://user-images.githubusercontent.com/112671464/202893453-e424b900-5257-4b91-b34d-d274abf0ecfe.png)
![ACB7C42C-BA19-4E90-9333-478BD8B4FAB1](https://user-images.githubusercontent.com/112671464/202893468-de268bbb-437e-44ab-a1d1-1acbf19a0b2f.png)
在数量过多时还会造成卡顿

### 复现此问题的步骤

无

### 有关的日志/输出

```raw
无
```

### 插件列表

```raw
无
```

**Comment by OEOTYAN** [comment]
使用错误，正常调用不会显示不全和产生卡顿，应当每2秒发送一次粒子。
